#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "config" / "tracked_entities.json"
WEB_OUTPUT_PATH = ROOT / "apps" / "web" / "src" / "generated" / "trackedEntities.ts"
WATCHLIST_OUTPUT_PATH = ROOT / "apps" / "api" / "src" / "frw_api" / "services" / "news" / "ticker_watchlist.generated.json"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate tracked entity artifacts from config/tracked_entities.json")
    parser.add_argument("--check", action="store_true", help="Fail when generated files differ")
    args = parser.parse_args()

    registry = _load_registry()
    outputs = {
        WEB_OUTPUT_PATH: _render_web_ts(registry),
        WATCHLIST_OUTPUT_PATH: _render_watchlist_json(registry),
    }
    if args.check:
        mismatches = [path for path, content in outputs.items() if not path.exists() or path.read_text() != content]
        if mismatches:
            for path in mismatches:
                print(f"stale generated artifact: {path.relative_to(ROOT)}")
            return 1
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return 0


def _load_registry() -> dict[str, Any]:
    payload = json.loads(REGISTRY_PATH.read_text())
    if not isinstance(payload, dict) or not isinstance(payload.get("entities"), list):
        raise ValueError("config/tracked_entities.json must contain an entities array")
    return payload


def _render_web_ts(registry: dict[str, Any]) -> str:
    entities = registry["entities"]
    public_entities = [_web_entity(entity) for entity in entities]
    payload = json.dumps(public_entities, ensure_ascii=False, indent=2)
    return (
        "/* eslint-disable */\n"
        "// Generated by scripts/generate_tracked_entities.py. Do not edit by hand.\n\n"
        "export type TrackedEntityRouteKind = \"ticker\" | \"reference_entity\" | \"unsupported\";\n\n"
        "export interface GeneratedTrackedEntity {\n"
        "  entityId: string;\n"
        "  symbol: string;\n"
        "  displaySymbol: string;\n"
        "  routeKey: string;\n"
        "  routeKind: TrackedEntityRouteKind;\n"
        "  name: string;\n"
        "  nameKo: string;\n"
        "  exchange: string;\n"
        "  assetType: \"Equity\" | \"ETF\" | \"Reference\";\n"
        "  currency: string;\n"
        "  country: string;\n"
        "  sector: string;\n"
        "  industry: string;\n"
        "  sectorKeys: string[];\n"
        "  tags: string[];\n"
        "  aliases: string[];\n"
        "  related: string[];\n"
        "  secCik?: string;\n"
        "  tradingViewSymbol?: string;\n"
        "  officialDomains: string[];\n"
        "  sourcePolicy: string;\n"
        "  thesisBull: string;\n"
        "  thesisBear: string;\n"
        "  invalidation: string;\n"
        "}\n\n"
        f"export const generatedTrackedEntities = {payload} as const satisfies readonly GeneratedTrackedEntity[];\n"
    )


def _web_entity(entity: dict[str, Any]) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "entityId": entity["entity_id"],
        "symbol": entity["symbol"],
        "displaySymbol": entity["display_symbol"],
        "routeKey": entity["route_key"],
        "routeKind": entity["route_kind"],
        "name": entity["name_en"],
        "nameKo": entity["name_ko"],
        "exchange": entity["exchange"],
        "assetType": entity["asset_type"],
        "currency": entity["currency"],
        "country": entity["country"],
        "sector": entity["sector"],
        "industry": entity["industry"],
        "sectorKeys": entity["sector_keys"],
        "tags": entity["tags"],
        "aliases": entity["aliases"],
        "related": entity["related_symbols"],
        "officialDomains": entity["official_domains"],
        "sourcePolicy": entity["source_policy"],
        "thesisBull": entity["thesis_bull"],
        "thesisBear": entity["thesis_bear"],
        "invalidation": entity["invalidation"],
    }
    if entity.get("sec_cik"):
        payload["secCik"] = str(entity["sec_cik"])
    if entity.get("tradingview_symbol"):
        payload["tradingViewSymbol"] = str(entity["tradingview_symbol"])
    return payload


def _render_watchlist_json(registry: dict[str, Any]) -> str:
    entities = []
    for entity in registry["entities"]:
        watch = dict(entity)
        watch["symbol"] = str(watch["symbol"]).upper()
        watch["legal_name"] = watch.get("legal_name") or watch["name_en"]
        watch["source_keys"] = [source["source_key"] for source in watch.get("sources", [])]
        entities.append(watch)
    return json.dumps({"version": registry.get("version", 1), "entities": entities}, indent=2, ensure_ascii=False) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
